@extends('layouts.app')

@section('title', 'Create Tournament')

@section('content')
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="card shadow border-0">
                
                <div class="card-header bg-primary text-white py-3 position-relative" style="z-index: 2;">
                    <h4 class="mb-0 fw-bold"><i class="fas fa-trophy me-2"></i>Create New Tournament</h4>
                </div>

                <div class="card-body p-4 bg-white position-relative" style="z-index: 1;">
                    <form action="{{ route('tournaments.store') }}" method="POST" id="tournamentForm" autocomplete="off">
                        @csrf
                        
                        {{-- Basic Info --}}
                        <div class="row g-3 mb-4">
                            <div class="col-md-6 position-relative">
                                <label class="fw-bold d-block mb-2">Tournament Name</label>
                                <input type="text" class="form-control" name="name" placeholder="e.g., Winter Cup 2025" required>
                            </div>
                            
                            <div class="col-md-3 position-relative">
                                <label class="fw-bold d-block mb-2">Start Date</label>
                                <input type="date" class="form-control" name="start_date" required value="{{ date('Y-m-d') }}" min="{{ date('Y-m-d') }}">
                            </div>
                            
                            <div class="col-md-3 position-relative">
                                <label class="fw-bold d-block mb-2">Size</label>
                                <select class="form-select" name="participant_count" id="participant_count" onchange="generateTeamInputs(this.value)">
                                    <option value="4">4 Teams</option>
                                    <option value="8" selected>8 Teams</option>
                                    <option value="16">16 Teams</option>
                                </select>
                            </div>
                        </div>

                        <hr class="my-4 text-muted">

                        {{-- Teams Section --}}
                        <div class="mb-4">
                            <h5 class="fw-bold mb-3">Team Registration</h5>
                            <p class="text-muted small mb-3"><i class="fas fa-info-circle me-1"></i> Start typing to select from your existing teams or create a new one.</p>
                            <div id="teamInputs" class="row g-3">
                                {{-- Generated by JS --}}
                            </div>
                        </div>

                        <div class="d-flex justify-content-end gap-2">
                            <a href="{{ route('tournaments.index') }}" class="btn btn-outline-secondary px-4">Cancel</a>
                            <button type="submit" class="btn btn-primary px-5 fw-bold">Generate Bracket</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{{-- PLAYER MODAL --}}
<div class="modal fade" id="playerModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" style="color: white;">Manage Roster: <span id="modalTeamName" class="text-warning fw-bold">Team #1</span></h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body bg-light">
                <input type="hidden" id="currentTeamIndex">
                
                <div class="table-responsive">
                    <table class="table table-bordered bg-white" id="playerTable">
                        <thead class="table-secondary">
                            <tr>
                                <th style="width: 50%">Player Name</th>
                                <th style="width: 20%">Number</th>
                                <th style="width: 20%">Position</th>
                                <th style="width: 10%">Action</th>
                            </tr>
                        </thead>
                        <tbody id="playerRows">
                            {{-- Rows added here --}}
                        </tbody>
                    </table>
                </div>
                <button type="button" class="btn btn-outline-primary w-100 mt-2" onclick="addPlayerRow()">
                    <i class="fas fa-plus-circle me-1"></i> Add Player
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success fw-bold px-4" onclick="saveRoster()">Save Roster</button>
            </div>
        </div>
    </div>
</div>

@push('styles')
{{-- 1. Load Tom Select CSS (Bootstrap 5 Version) --}}
<link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.bootstrap5.min.css" rel="stylesheet">

<style>
    /* FIX: Make Tom Select fill the flex space inside .input-group 
       This solves the layout issue where the input shrank or broke.
    */
    .input-group .ts-wrapper {
        flex-grow: 1;
        border: none;
        padding: 0;
    }

    /* Remove double borders to make it blend with input-group-text and button */
    .input-group .ts-control {
        border-radius: 0; 
        border-left: 0;
        height: 100%; /* Ensure it matches the button height */
        display: flex;
        align-items: center;
    }

    /* Optional: Ensure the dropdown appears above other elements */
    .ts-dropdown {
        z-index: 1060 !important; 
    }
</style>
@endpush

@push('scripts')
{{-- 2. Load Tom Select JS --}}
<script src="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/js/tom-select.complete.min.js"></script>

<script>
    // Load Data
    const availableTeams = @json($availableTeams ?? []);
    
    // Convert to format TomSelect likes (array of objects with 'value' and 'text')
    // We add 'roster' data here so we can access it during selection
    const teamOptions = availableTeams.map(t => ({
        id: t.name,
        title: t.name,
        roster: t.roster,
        count: t.roster.length
    }));

    let playerModalInstance = null;
    let rosters = {};
    let selectInstances = {}; // Store TomSelect instances if we need to access them later

    function generateTeamInputs(count) {
        const container = document.getElementById('teamInputs');
        container.innerHTML = '';
        
        // Clear old rosters/instances to prevent memory leaks or logic errors
        rosters = {}; 
        selectInstances = {};

        for (let i = 1; i <= count; i++) {
            const div = document.createElement('div');
            div.className = 'col-md-6';
            
            // Note: We use a <select> now instead of <input>
            div.innerHTML = `
                <div class="input-group shadow-sm h-100">
                    <span class="input-group-text bg-light fw-bold text-secondary" style="min-width: 120px;">
                        <i class="fas fa-shield-alt me-2 text-primary"></i> Team ${i}
                    </span>

                    <select id="team-select-${i}" name="teams[${i}][name]" placeholder="Select or type team..."></select>

                    <button type="button" class="btn btn-outline-primary" onclick="openPlayerModal(${i})">
                        <i class="fas fa-user-plus"></i>
                        <span class="badge bg-primary ms-1 rounded-pill" id="count-${i}">0</span>
                    </button>
                </div>
                
                <input type="hidden" name="teams[${i}][players]" id="roster-input-${i}" value="[]">
            `;
            container.appendChild(div);

            // --- Initialize Tom Select for this row ---
            initTomSelect(i);
        }
    }

    function initTomSelect(index) {
        const selector = `#team-select-${index}`;
        
        selectInstances[index] = new TomSelect(selector, {
            options: teamOptions,
            valueField: 'id',
            labelField: 'title',
            searchField: 'title',
            create: true, // Allow user to type new names
            maxItems: 1,
            placeholder: "Select or type team...",
            
            // Custom Look for the Dropdown items (Matches your design)
            render: {
                option: function(data, escape) {
                    return `<div class="d-flex justify-content-between align-items-center py-2">
                                <span class="fw-bold">${escape(data.title)}</span>
                                ${data.count !== undefined 
                                    ? `<span class="badge bg-light text-secondary rounded-pill border small">${escape(data.count)} players</span>` 
                                    : '<span class="badge bg-light text-secondary rounded-pill border small">New</span>'}
                            </div>`;
                },
                item: function(data, escape) {
                    return `<div>${escape(data.title)}</div>`;
                }
            },

            // Event: When user selects or types a team
            onChange: function(value) {
                handleTeamSelection(index, value);
            }
        });
    }

    function handleTeamSelection(index, teamName) {
        // 1. Find if this team exists in our DB
        const existingTeam = availableTeams.find(t => t.name === teamName);
        
        // 2. Logic to update roster inputs
        if (existingTeam && existingTeam.roster.length > 0) {
            // It's a DB team, load their roster
            rosters[index] = JSON.parse(JSON.stringify(existingTeam.roster)); // Deep copy
        } else {
            // It's a brand new name OR a DB team with 0 players
            // We do NOT clear the roster if the user just renamed the text in the box, 
            // but for a strict "Select" logic, usually switching teams clears the roster.
            rosters[index] = [];
        }

        // 3. Update Hidden Input and UI Badge
        updateRosterData(index);
    }

    function updateRosterData(index) {
        const currentRoster = rosters[index] || [];
        document.getElementById(`roster-input-${index}`).value = JSON.stringify(currentRoster);
        document.getElementById(`count-${index}`).innerText = currentRoster.length;
    }

    // --- Modal Logic (Mostly unchanged, just connected to new variables) ---

    function openPlayerModal(index) {
        document.getElementById('currentTeamIndex').value = index;
        
        // Get name from Tom Select instance
        const tom = selectInstances[index];
        const currentName = tom ? tom.getValue() : `Team #${index}`;
        
        document.getElementById('modalTeamName').innerText = currentName || `Team #${index}`;
        
        const tbody = document.getElementById('playerRows');
        tbody.innerHTML = '';

        const currentRoster = rosters[index] || [];
        
        if (currentRoster.length === 0) {
            addPlayerRow(); 
        } else {
            currentRoster.forEach(p => addPlayerRow(p.name, p.number, p.pos));
        }

        const modalEl = document.getElementById('playerModal');
        if (!playerModalInstance) {
            playerModalInstance = new bootstrap.Modal(modalEl);
        }
        playerModalInstance.show();
    }

    function addPlayerRow(name = '', number = '', pos = '') {
        const tbody = document.getElementById('playerRows');
        const row = document.createElement('tr');
        row.innerHTML = `
            <td><input type="text" class="form-control" placeholder="Name" value="${name}"></td>
            <td><input type="number" class="form-control" placeholder="#" value="${number}"></td>
            <td>
                <select class="form-select">
                    <option value="PG" ${pos==='PG'?'selected':''}>PG</option>
                    <option value="SG" ${pos==='SG'?'selected':''}>SG</option>
                    <option value="SF" ${pos==='SF'?'selected':''}>SF</option>
                    <option value="PF" ${pos==='PF'?'selected':''}>PF</option>
                    <option value="C" ${pos==='C'?'selected':''}>C</option>
                </select>
            </td>
            <td class="text-center"><button type="button" class="btn btn-outline-danger btn-sm" onclick="this.closest('tr').remove()"><i class="fas fa-times"></i></button></td>
        `;
        tbody.appendChild(row);
    }

    function saveRoster() {
        const index = document.getElementById('currentTeamIndex').value;
        const rows = document.querySelectorAll('#playerRows tr');
        const newRoster = [];

        rows.forEach(row => {
            const inputs = row.querySelectorAll('input, select');
            if(inputs[0] && inputs[0].value.trim() !== '') {
                newRoster.push({
                    name: inputs[0].value,
                    number: inputs[1].value,
                    pos: inputs[2].value
                });
            }
        });

        rosters[index] = newRoster;
        updateRosterData(index); // Helper function updates UI and Hidden Input

        if (playerModalInstance) {
            playerModalInstance.hide();
        }
    }

    document.addEventListener('DOMContentLoaded', () => generateTeamInputs(8));
</script>
@endpush
@endsection